name: Deploy Backend to Elastic Beanstalk

on:
  push:
    branches: [ "main", "db_and_deploy" ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend-eb.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke checks
        run: |
          python - <<'PY'
          import importlib
          import sys
          for m in ["app.api", "app.graph.build_graph", "app.graph.agents"]:
              importlib.import_module(m)
          print("Smoke import OK")
          PY

      - name: Zip artifact
        run: |
          zip -r ../backend.zip . -x "__pycache__/*" -x "*.pyc"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: backend-${{ github.run_number }}
          deployment_package: backend.zip
